#!/bin/bash
# -*- tab-width: 4; encoding: utf-8 -*-
#
## @file
## @author Damien Nadé <bash-argsparse@livna.org>
## @brief Bash Doxgen Unit Test
## @copyright WTFPLv2
## @version 1

declare -r readonly=readonly-value
declare -a array
declare -a assigned_array=(1 2)
declare -A associative_array
declare -A assigned_associative_array=([x]=1 [y]=2)
declare -i integer
declare -i assigned_integer=2
declare -x declared_exported
declare -x assigned_declared_exported=1

export exported
export assigned_exported=1

## @fn function_1()
## @brief 1st function
## @param param1 first parameter
function_1() {
	bogus
	bogus2;
}
